name: project_dermatoma
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive_flutter:
  states_rebuilder:
  english_words:
  google_fonts:
  flutter_native_splash:
  file_picker:
  flex_color_scheme:
  uuid:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons:
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    # - lib/assets/fonts/
flutter_native_splash:
  image: "assets/skin.png"
  color: "#000000"
  # background_image: "lib/assets/default.png"

flutter_icons:
  android: "launcher_icon"
  # ios: true
  image_path: "assets/skin.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/skin.png"
  #   background_color: "#hexcode"
  #   theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/skin.png"
    icon_size: 48 # min:48, max:256, default: 48
  # macos:
  #   generate: true
  #   image_path: "path/to/image.png"